//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр рабочих элементов.
        /// </summary>
        public static string AP_MainFilter_ToolTip {
            get {
                return ResourceManager.GetString("AP_MainFilter_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        public static string AP_MainView_Area_Column {
            get {
                return ResourceManager.GetString("AP_MainView_Area_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент.
        /// </summary>
        public static string AP_MainView_Element_Column {
            get {
                return ResourceManager.GetString("AP_MainView_Element_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AP_MainView_Id_Column {
            get {
                return ResourceManager.GetString("AP_MainView_Id_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итерация.
        /// </summary>
        public static string AP_MainView_Iteration_Column {
            get {
                return ResourceManager.GetString("AP_MainView_Iteration_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать список элементов.
        /// </summary>
        public static string AP_MainView_List_ToolTip {
            get {
                return ResourceManager.GetString("AP_MainView_List_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string AP_MainView_State_Column {
            get {
                return ResourceManager.GetString("AP_MainView_State_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать таблицу.
        /// </summary>
        public static string AP_MainView_Table_ToolTip {
            get {
                return ResourceManager.GetString("AP_MainView_Table_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string AP_MainView_Title_Column {
            get {
                return ResourceManager.GetString("AP_MainView_Title_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string AS_About {
            get {
                return ResourceManager.GetString("AS_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор:.
        /// </summary>
        public static string AS_About_Author {
            get {
                return ResourceManager.GetString("AS_About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графики и визуализация данных.
        /// </summary>
        public static string AS_About_Charts {
            get {
                return ResourceManager.GetString("AS_About_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтрация для таблицы.
        /// </summary>
        public static string AS_About_DataFilter {
            get {
                return ResourceManager.GetString("AS_About_DataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница на GitHub.
        /// </summary>
        public static string AS_About_Github_page {
            get {
                return ResourceManager.GetString("AS_About_Github_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа создана для помощи в работе с TFS .
        /// </summary>
        public static string AS_About_Help {
            get {
                return ResourceManager.GetString("AS_About_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использует следующие библиотеки:.
        /// </summary>
        public static string AS_About_libs {
            get {
                return ResourceManager.GetString("AS_About_libs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построена на базе.
        /// </summary>
        public static string AS_About_MaterialRef {
            get {
                return ResourceManager.GetString("AS_About_MaterialRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя: .
        /// </summary>
        public static string AS_About_Name {
            get {
                return ResourceManager.GetString("AS_About_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя TFS проекта: .
        /// </summary>
        public static string AS_About_ProjectName {
            get {
                return ResourceManager.GetString("AS_About_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темы и стили.
        /// </summary>
        public static string AS_About_themesAndStyles {
            get {
                return ResourceManager.GetString("AS_About_themesAndStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string AS_Actions {
            get {
                return ResourceManager.GetString("AS_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string AS_Add {
            get {
                return ResourceManager.GetString("AS_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мастер добавления правила.
        /// </summary>
        public static string AS_AddRule_Master_Title {
            get {
                return ResourceManager.GetString("AS_AddRule_Master_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мастер создания правила.
        /// </summary>
        public static string AS_AddRuleMaster {
            get {
                return ResourceManager.GetString("AS_AddRuleMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило запрашивает мои активные таски и проверяет, указана ли в них текущая итерация..
        /// </summary>
        public static string AS_AllTasksInCurrentIteration_Descr {
            get {
                return ResourceManager.GetString("AS_AllTasksInCurrentIteration_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спрашивать каждый раз.
        /// </summary>
        public static string AS_AskEveryTime {
            get {
                return ResourceManager.GetString("AS_AskEveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждый час программа будет спрашивать пользователя какую задачу выбрать для списания..
        /// </summary>
        public static string AS_AskEveryTime_Descr {
            get {
                return ResourceManager.GetString("AS_AskEveryTime_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматическое наблюдение.
        /// </summary>
        public static string AS_AutoObserve {
            get {
                return ResourceManager.GetString("AS_AutoObserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступная емкость.
        /// </summary>
        public static string AS_AvailableCapacity {
            get {
                return ResourceManager.GetString("AS_AvailableCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборки.
        /// </summary>
        public static string AS_BuidlQueue_Button {
            get {
                return ResourceManager.GetString("AS_BuidlQueue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя сборки.
        /// </summary>
        public static string AS_BuildName {
            get {
                return ResourceManager.GetString("AS_BuildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список поставленных в очередь сборок.
        /// </summary>
        public static string AS_BuildQueue {
            get {
                return ResourceManager.GetString("AS_BuildQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборки.
        /// </summary>
        public static string AS_Builds {
            get {
                return ResourceManager.GetString("AS_Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время от времени программа будет запрашивать текущие сборки. При изменении каких-либо свойств (сборка завершилась или изменила свой статус), появится уведомление внизу экрана..
        /// </summary>
        public static string AS_BuildsObserve_Help {
            get {
                return ResourceManager.GetString("AS_BuildsObserve_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string AS_Cancel {
            get {
                return ResourceManager.GetString("AS_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило проверяет мои рабочие элементы на наличие указанной области..
        /// </summary>
        public static string AS_CheckArea_Descr {
            get {
                return ResourceManager.GetString("AS_CheckArea_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить соединение.
        /// </summary>
        public static string AS_CheckConnection {
            get {
                return ResourceManager.GetString("AS_CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сборку.
        /// </summary>
        public static string AS_ChooseBuild {
            get {
                return ResourceManager.GetString("AS_ChooseBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбираем сами.
        /// </summary>
        public static string AS_ChooseByMyOwn {
            get {
                return ResourceManager.GetString("AS_ChooseByMyOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите к чему привязать задачу.
        /// </summary>
        public static string AS_ChooseParentItem {
            get {
                return ResourceManager.GetString("AS_ChooseParentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите проект.
        /// </summary>
        public static string AS_ChooseProject {
            get {
                return ResourceManager.GetString("AS_ChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбираем случайно.
        /// </summary>
        public static string AS_ChooseRandomly {
            get {
                return ResourceManager.GetString("AS_ChooseRandomly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите рабочий элемент:.
        /// </summary>
        public static string AS_ChooseTask {
            get {
                return ResourceManager.GetString("AS_ChooseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите элемент для списания времени.
        /// </summary>
        public static string AS_ChooseWriteoffTask {
            get {
                return ResourceManager.GetString("AS_ChooseWriteoffTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите дату, после которой review считаются устаревшими:.
        /// </summary>
        public static string AS_ChoseOldReviewDate {
            get {
                return ResourceManager.GetString("AS_ChoseOldReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string AS_Close {
            get {
                return ResourceManager.GetString("AS_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть успешные запросы проверки кода.
        /// </summary>
        public static string AS_CloseCompletedReviewes {
            get {
                return ResourceManager.GetString("AS_CloseCompletedReviewes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть устаревшие запросы на проверку кода.
        /// </summary>
        public static string AS_CloseOldReviews {
            get {
                return ResourceManager.GetString("AS_CloseOldReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросы на проверку моего кода (Review Request).
        /// </summary>
        public static string AS_CodeRequest_Header {
            get {
                return ResourceManager.GetString("AS_CodeRequest_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросили проверку кода.
        /// </summary>
        public static string AS_CodeReviewRequested {
            get {
                return ResourceManager.GetString("AS_CodeReviewRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось подключиться.
        /// </summary>
        public static string AS_ConnectError {
            get {
                return ResourceManager.GetString("AS_ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение установлено.
        /// </summary>
        public static string AS_ConnectionEstablished {
            get {
                return ResourceManager.GetString("AS_ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string AS_Continue {
            get {
                return ResourceManager.GetString("AS_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать свой.
        /// </summary>
        public static string AS_CreateOwn {
            get {
                return ResourceManager.GetString("AS_CreateOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие сборки:.
        /// </summary>
        public static string AS_CurrentBuilds {
            get {
                return ResourceManager.GetString("AS_CurrentBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее подключение:.
        /// </summary>
        public static string AS_CurrentConnection {
            get {
                return ResourceManager.GetString("AS_CurrentConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие статусы.
        /// </summary>
        public static string AS_CurrentStatuses {
            get {
                return ResourceManager.GetString("AS_CurrentStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пользователь.
        /// </summary>
        public static string AS_CurrentUser {
            get {
                return ResourceManager.GetString("AS_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневная норма часов:.
        /// </summary>
        public static string AS_DailyWorkHours {
            get {
                return ResourceManager.GetString("AS_DailyWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во рабочих часов в день:.
        /// </summary>
        public static string AS_DailyWriteOffHours {
            get {
                return ResourceManager.GetString("AS_DailyWriteOffHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключено.
        /// </summary>
        public static string AS_Disabled {
            get {
                return ResourceManager.GetString("AS_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списывание времени отключено.
        /// </summary>
        public static string AS_Disabled_Descr {
            get {
                return ResourceManager.GetString("AS_Disabled_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название не может быть пустым.
        /// </summary>
        public static string AS_EmptyName_Error {
            get {
                return ResourceManager.GetString("AS_EmptyName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить.
        /// </summary>
        public static string AS_Enable {
            get {
                return ResourceManager.GetString("AS_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставьте необходимое имя области.
        /// </summary>
        public static string AS_EnterAreaPath {
            get {
                return ResourceManager.GetString("AS_EnterAreaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название задачи.
        /// </summary>
        public static string AS_EnterTaskName {
            get {
                return ResourceManager.GetString("AS_EnterTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите строку подключения к Team Foundation Server.
        /// </summary>
        public static string AS_EnterTfsUri {
            get {
                return ResourceManager.GetString("AS_EnterTfsUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать кол-во часов для списания.
        /// </summary>
        public static string AS_EnterWriteOffHours {
            get {
                return ResourceManager.GetString("AS_EnterWriteOffHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть элементы.
        /// </summary>
        public static string AS_Filter_IgnoredIds {
            get {
                return ResourceManager.GetString("AS_Filter_IgnoredIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние.
        /// </summary>
        public static string AS_Filter_WorkItemStates {
            get {
                return ResourceManager.GetString("AS_Filter_WorkItemStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы рабочих элементов.
        /// </summary>
        public static string AS_Filter_WorkTypes {
            get {
                return ResourceManager.GetString("AS_Filter_WorkTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        public static string AS_Finish {
            get {
                return ResourceManager.GetString("AS_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первое подключение.
        /// </summary>
        public static string AS_FirstConnection {
            get {
                return ResourceManager.GetString("AS_FirstConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брать из TFS.
        /// </summary>
        public static string AS_GetCapacityFromTfs {
            get {
                return ResourceManager.GetString("AS_GetCapacityFromTfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глобальная настройка.
        /// </summary>
        public static string AS_GlobalVariable {
            get {
                return ResourceManager.GetString("AS_GlobalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        public static string AS_History {
            get {
                return ResourceManager.GetString("AS_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Важная вещь, посмотри.
        /// </summary>
        public static string AS_ImportantNotice {
            get {
                return ResourceManager.GetString("AS_ImportantNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменились следующие элементы:.
        /// </summary>
        public static string AS_ItemsChanged {
            get {
                return ResourceManager.GetString("AS_ItemsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время между обновлениями рабочих элементов (в минутах).
        /// </summary>
        public static string AS_ItemUpdatePeriod {
            get {
                return ResourceManager.GetString("AS_ItemUpdatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнее изменение.
        /// </summary>
        public static string AS_LastChangeDate {
            get {
                return ResourceManager.GetString("AS_LastChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        public static string AS_Load {
            get {
                return ResourceManager.GetString("AS_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальная очередь сборок в случае, если очередь на агенте не работает.
        ///      
        ///Как только все текущие сборки закончатся, программа отправляет первую сборку в локальной очереди агентам..
        /// </summary>
        public static string AS_LocalQueue_Help {
            get {
                return ResourceManager.GetString("AS_LocalQueue_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь к файлу логов.
        /// </summary>
        public static string AS_LogPath {
            get {
                return ResourceManager.GetString("AS_LogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка с логами программы.
        /// </summary>
        public static string AS_LogsFolderPath {
            get {
                return ResourceManager.GetString("AS_LogsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть элемент.
        /// </summary>
        public static string AS_MainView_ItemMenu_Ignore {
            get {
                return ResourceManager.GetString("AS_MainView_ItemMenu_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответил &apos;Looks Good&apos; на {0} запросов, созданные до {1}.
        /// </summary>
        public static string AS_Mask_ResponseClosed {
            get {
                return ResourceManager.GetString("AS_Mask_ResponseClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыто {0} мои запросов кода,которые были проверены.
        /// </summary>
        public static string AS_Mask_ReviewClosed {
            get {
                return ResourceManager.GetString("AS_Mask_ReviewClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудосгорание за месяц.
        /// </summary>
        public static string AS_MonthlyCapacity {
            get {
                return ResourceManager.GetString("AS_MonthlyCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месячное списание часов.
        /// </summary>
        public static string AS_MonthlySchedule {
            get {
                return ResourceManager.GetString("AS_MonthlySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперёд.
        /// </summary>
        public static string AS_MoveNext {
            get {
                return ResourceManager.GetString("AS_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string AS_MovePreviouse {
            get {
                return ResourceManager.GetString("AS_MovePreviouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои рабочие элементы:.
        /// </summary>
        public static string AS_MyWorkItems {
            get {
                return ResourceManager.GetString("AS_MyWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые баги.
        /// </summary>
        public static string AS_NewBugs {
            get {
                return ResourceManager.GetString("AS_NewBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая сборка.
        /// </summary>
        public static string AS_NewBuild {
            get {
                return ResourceManager.GetString("AS_NewBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые рабочие элементы были назначены.
        /// </summary>
        public static string AS_NewItemsAssigned {
            get {
                return ResourceManager.GetString("AS_NewItemsAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая работа.
        /// </summary>
        public static string AS_NewWork {
            get {
                return ResourceManager.GetString("AS_NewWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        public static string AS_Next {
            get {
                return ResourceManager.GetString("AS_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочий элемент не является таском.
        /// </summary>
        public static string AS_NotATask_Error {
            get {
                return ResourceManager.GetString("AS_NotATask_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка не является веб-адресом.
        /// </summary>
        public static string AS_NotAWebAddress_Error {
            get {
                return ResourceManager.GetString("AS_NotAWebAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наблюдаемые рабочие элементы.
        /// </summary>
        public static string AS_ObservableItems_Title {
            get {
                return ResourceManager.GetString("AS_ObservableItems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество дней, после которого запрос на проверку кода считается устаревшим.
        /// </summary>
        public static string AS_OldReviewDays {
            get {
                return ResourceManager.GetString("AS_OldReviewDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string AS_Open {
            get {
                return ResourceManager.GetString("AS_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть свойства.
        /// </summary>
        public static string AS_OpenProperties {
            get {
                return ResourceManager.GetString("AS_OpenProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя параметра.
        /// </summary>
        public static string AS_ParamName {
            get {
                return ResourceManager.GetString("AS_ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        public static string AS_Params {
            get {
                return ResourceManager.GetString("AS_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать кол-во запланированных часов на работу.
        /// </summary>
        public static string AS_PlannedTime_Error {
            get {
                return ResourceManager.GetString("AS_PlannedTime_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запланированное время работы.
        /// </summary>
        public static string AS_PlannedWorkTime {
            get {
                return ResourceManager.GetString("AS_PlannedWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запланированое списание времени.
        /// </summary>
        public static string AS_PlannedWriteoffTime {
            get {
                return ResourceManager.GetString("AS_PlannedWriteoffTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа.
        /// </summary>
        public static string AS_Program {
            get {
                return ResourceManager.GetString("AS_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя свойства.
        /// </summary>
        public static string AS_PropName {
            get {
                return ResourceManager.GetString("AS_PropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа найдет все активные таски назначенные пользователю и выберет один из них случайно..
        /// </summary>
        public static string AS_Random_Descr {
            get {
                return ResourceManager.GetString("AS_Random_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таймаут обновления.
        /// </summary>
        public static string AS_RefreshTimeout {
            get {
                return ResourceManager.GetString("AS_RefreshTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставшаяся работа.
        /// </summary>
        public static string AS_RemainingWork {
            get {
                return ResourceManager.GetString("AS_RemainingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string AS_Remove {
            get {
                return ResourceManager.GetString("AS_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заменить правило?.
        /// </summary>
        public static string AS_ReplaceRule_Asking {
            get {
                return ResourceManager.GetString("AS_ReplaceRule_Asking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замена.
        /// </summary>
        public static string AS_Replacing {
            get {
                return ResourceManager.GetString("AS_Replacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запросы.
        /// </summary>
        public static string AS_Reqiests {
            get {
                return ResourceManager.GetString("AS_Reqiests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во запросов.
        /// </summary>
        public static string AS_RequestCount {
            get {
                return ResourceManager.GetString("AS_RequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата запроса.
        /// </summary>
        public static string AS_RequestDate {
            get {
                return ResourceManager.GetString("AS_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем запрошен.
        /// </summary>
        public static string AS_RequestedBy {
            get {
                return ResourceManager.GetString("AS_RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во ответов.
        /// </summary>
        public static string AS_ResponseCount {
            get {
                return ResourceManager.GetString("AS_ResponseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответы.
        /// </summary>
        public static string AS_Responses {
            get {
                return ResourceManager.GetString("AS_Responses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверяющий.
        /// </summary>
        public static string AS_Reviewer {
            get {
                return ResourceManager.GetString("AS_Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверяющие.
        /// </summary>
        public static string AS_Reviewers {
            get {
                return ResourceManager.GetString("AS_Reviewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string AS_Settings {
            get {
                return ResourceManager.GetString("AS_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из программы.
        /// </summary>
        public static string AS_ShutdownProgram {
            get {
                return ResourceManager.GetString("AS_ShutdownProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустить списание времени?.
        /// </summary>
        public static string AS_SkipWriteOff {
            get {
                return ResourceManager.GetString("AS_SkipWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списание времени.
        /// </summary>
        public static string AS_SkipWriteOff_Title {
            get {
                return ResourceManager.GetString("AS_SkipWriteOff_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string AS_Status {
            get {
                return ResourceManager.GetString("AS_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборка {0} собрана успешно.
        /// </summary>
        public static string AS_StrFormat_BuildedSuccecfully {
            get {
                return ResourceManager.GetString("AS_StrFormat_BuildedSuccecfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборка {0} завершена со статусом {1}.
        /// </summary>
        public static string AS_StrFormat_BuildedWithError {
            get {
                return ResourceManager.GetString("AS_StrFormat_BuildedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затрачено {0} часов.
        /// </summary>
        public static string AS_StrFormat_CompletedHours {
            get {
                return ResourceManager.GetString("AS_StrFormat_CompletedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневной предел: {0} ч.
        /// </summary>
        public static string AS_StrFormat_DailyMax {
            get {
                return ResourceManager.GetString("AS_StrFormat_DailyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневная занятость: {0} ч.
        /// </summary>
        public static string AS_StrFormat_DailyWorkTime {
            get {
                return ResourceManager.GetString("AS_StrFormat_DailyWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ч.
        /// </summary>
        public static string AS_StrFormat_Hours {
            get {
                return ResourceManager.GetString("AS_StrFormat_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось {0} ч.
        /// </summary>
        public static string AS_StrFormat_RemainingHours {
            get {
                return ResourceManager.GetString("AS_StrFormat_RemainingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списано: {0} ч.
        /// </summary>
        public static string AS_StrFormat_WrittenOff {
            get {
                return ResourceManager.GetString("AS_StrFormat_WrittenOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание рабочего элемента.
        /// </summary>
        public static string AS_TaskCreation {
            get {
                return ResourceManager.GetString("AS_TaskCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS соединение.
        /// </summary>
        public static string AS_TfsConnection_Title {
            get {
                return ResourceManager.GetString("AS_TfsConnection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные из TFS.
        /// </summary>
        public static string AS_TfsInfo {
            get {
                return ResourceManager.GetString("AS_TfsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string AS_Time {
            get {
                return ResourceManager.GetString("AS_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудозатраты сегодня.
        /// </summary>
        public static string AS_TodayWriteOff {
            get {
                return ResourceManager.GetString("AS_TodayWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уверен, что задачу нельзя разбить на меньшие части?.
        /// </summary>
        public static string AS_TooBigTask_Asking {
            get {
                return ResourceManager.GetString("AS_TooBigTask_Asking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        public static string AS_Total {
            get {
                return ResourceManager.GetString("AS_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месячная история трудосгорания.
        /// </summary>
        public static string AS_Trand_Title {
            get {
                return ResourceManager.GetString("AS_Trand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудосгорания.
        /// </summary>
        public static string AS_Treng_History {
            get {
                return ResourceManager.GetString("AS_Treng_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string AS_TryChange {
            get {
                return ResourceManager.GetString("AS_TryChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string AS_TryCreate {
            get {
                return ResourceManager.GetString("AS_TryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string AS_Update {
            get {
                return ResourceManager.GetString("AS_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать пресеты.
        /// </summary>
        public static string AS_UseDefaults {
            get {
                return ResourceManager.GetString("AS_UseDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string AS_Value {
            get {
                return ResourceManager.GetString("AS_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа спросит пользователя над какой задачей он работает. Далее часы будут списываться в эту задачу до предела планируемых часов. Затем диалог вызовется снова.
        /// </summary>
        public static string AS_Watch_Descr {
            get {
                return ResourceManager.GetString("AS_Watch_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина рабочего дня:.
        /// </summary>
        public static string AS_WorkDayTime {
            get {
                return ResourceManager.GetString("AS_WorkDayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудосгорание.
        /// </summary>
        public static string AS_WorkHoursTracking {
            get {
                return ResourceManager.GetString("AS_WorkHoursTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр рабочих элементов.
        /// </summary>
        public static string AS_WorkItemFilter {
            get {
                return ResourceManager.GetString("AS_WorkItemFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа время от времени будет запрашивать актуальные рабочие элементы, которые привязаны к текущему пользователю. При наличии любых изменений, к примеру, когда рабочий элемент назначается на другого человека, возникнет всплывающее уведомление с сылкой на изменённый элемент..
        /// </summary>
        public static string AS_WorkItemObserve_Help {
            get {
                return ResourceManager.GetString("AS_WorkItemObserve_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите время между повторными запросами (сек).
        /// </summary>
        public static string AS_WorkItemObserve_Time {
            get {
                return ResourceManager.GetString("AS_WorkItemObserve_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила рабочих элементов:.
        /// </summary>
        public static string AS_WorkItemRules {
            get {
                return ResourceManager.GetString("AS_WorkItemRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочие элементы.
        /// </summary>
        public static string AS_WorkItems {
            get {
                return ResourceManager.GetString("AS_WorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Динамика списания часов.
        /// </summary>
        public static string AS_WriteOff_Trend {
            get {
                return ResourceManager.GetString("AS_WriteOff_Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списать часы.
        /// </summary>
        public static string AS_WriteOffHours {
            get {
                return ResourceManager.GetString("AS_WriteOffHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите кол-во часов для списания.
        /// </summary>
        public static string AS_WriteOffHours_Hint {
            get {
                return ResourceManager.GetString("AS_WriteOffHours_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стратегия списывания времени:.
        /// </summary>
        public static string AS_WroteOffStrategy {
            get {
                return ResourceManager.GetString("AS_WroteOffStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как выбираем рабочий элемент для запланированного списания часов?.
        /// </summary>
        public static string AS_WroteOffStrategy_Asking {
            get {
                return ResourceManager.GetString("AS_WroteOffStrategy_Asking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
